### ISSUE TITLE
Main Branch 관련하여 공지합니다. 

### ISSUE THREAD

**Issue by jithhuP** [jithhuP/PowerBall#11]
Main Branch는 완성 및 오류가 없는 코드를 위주로 올려주세요. 미완성 작업 및 Sample 코드는 Test Branch 및 Main_menu_add Branch에서 작업해주시길 바랍니다. 

또한 작업이 끝나더라도 Test Branch 및 Main_menu_add Branch 에서 코드를 삭제하거나 Branch를 삭제하는 것은 기록에 영향이 있을 수 있으니 꼭 조심해주세요.

작업한 내용은 꼭 Issue를 작성해주세요. 사소한 내용도 좋으니 자신의 작업을 팀원에게 공유해주세요. (숨기는 노력보단 보여주는 노력이 도움이 됩니다.)

**Comment by jithhuP** [comment]
추가) 제가 현재 Main branch에 올린 테스트용 코드는 빠른 시간 내에 완성 코드를 작성해보겠습니다. 따라서 지우지 말아주세요.

**Comment by jominking** [comment]
네, 확인했습니다.
