### ISSUE TITLE
App 에 차별점을 주기 위한 추가 기능 제안

### ISSUE THREAD

**Issue by 1Parksanghyun** [jithhuP/PowerBall#14]
App에 차별점을 주기 위한 추가 기능을 아래 Comment에 답변을 해주시길 바랍니다

해당 이슈는 4/24일까지 유효합니다.

**Comment by 1Parksanghyun** [comment]
운으로 결정되는 간단한 미니게임, 간단하게 술래를 뽑는 기능

**Comment by jominking** [comment]
당첨 지역을 자료 수집 후 통계를 내어 지역 추천하기

**Comment by jithhuP** [comment]
AI 챗봇(chat gpt)를 사용하여 앱에서 사용자가 원하는 질문을 할수 있는 환경을 만들어준다.

기대점:
1. 재미
2. 어느정도 신뢰감 상승
3. 앱 실행률 상승
