### ISSUE TITLE
PPT 자료입니다.

### ISSUE THREAD

**Issue by jominking** [jithhuP/PowerBall#16]
[POWER BALL.pptx](https://github.com/jithhuP/PowerBall/files/11303075/POWER.BALL.pptx)
부족한 부분이나 더 필요한 내용이 있으시면 말씀해주세요. 내용 수정, 보완해서 다시 올리겠습니다.

**Comment by jithhuP** [comment]
확인했습니다. 필요할 시 issue로 연락드리겠습니다.
