### ISSUE TITLE
PPT 자료

### ISSUE THREAD

**Issue by 1Parksanghyun** [jithhuP/PowerBall#17]
[오픈소스프로젝트_박상현_1.pptx](https://github.com/jithhuP/PowerBall/files/11303528/_._1.pptx)

자료 제출합니다

Problem 부분 Input, Output 추가 내용이 필요합니다
Input은 Output 을 얻기위해 넣어야 할 데이터
Output은 보여줄 결과물 입니다

디자인 필요하면 저한테 연락주세요

**Comment by jithhuP** [comment]
확인했습니다. 필요할 시 issue로 연락드리겠습니다.
