### ISSUE TITLE
자료조사 링크 파일

### ISSUE THREAD

**Issue by jithhuP** [jithhuP/PowerBall#18]
[자료조사.txt](https://github.com/jithhuP/PowerBall/files/11319445/default.txt)

필요한 내용을 가지고 있는 사이트의 주소를 담은 파일입니다.

시장 조사 + 통계 방법 + 알고리즘 구현 등등 도움이 될 내용을 담고 있습니다.

**Comment by jominking** [comment]
네, 확인했습니다.
