### ISSUE TITLE
통계 branch 하나 만들겠습니다.

### ISSUE THREAD

**Issue by jominking** [jithhuP/PowerBall#23]
통계 branch 하나 만들어서 통계 부분 코드 업로드 하겠습니다.

**Comment by jominking** [comment]
소스 코드 파일은 어떻게 올리나요?

**Comment by jithhuP** [comment]
소스코드 파일은 관리하시는 작업에서 git을 연결시킨 후 commit & push로 올릴 수 있습니다.

예를 들어서 Vs code에서 github을 연결시킬 수 있고 연결 후 commit과 push로 오픈소스 관리를 할 수 있습니다.

**Comment by jominking** [comment]
제가 올린 cpp파일 옳게 올려진 것인가요?

**Comment by jominking** [comment]
제가 한 작업은 어디에 request 시켜야 하나요?
