### ISSUE TITLE
git push 질문있습니다.

### ISSUE THREAD

**Issue by jominking** [jithhuP/PowerBall#24]
android studio에 git 연동하고 commit까지 한 후 push 과정에서 막혔습니다. 제 통계 branch가 아닌 main에 push를 할 것 같아서 그런데 혹시 push 과정 알려주실 수 있겠습니까? 검색해도 나오지 않아 질문합니다.

**Comment by 1Parksanghyun** [comment]
[push 방.zip](https://github.com/jithhuP/PowerBall/files/11404551/push.zip)

**Comment by 1Parksanghyun** [comment]
체크아웃으로 통계 브랜치로 이동한 다음 수정된 파일을 커밋하시고 푸시 하시면 됩니다
그리고 지금 통계 브랜치가 제 쪽에서는 없어서 통계 브랜치가 없는 것일 수도 잇습니다.

**Comment by jominking** [comment]
감사합니다. 우선 방법 대로 해보겠습니다.
