### ISSUE TITLE
5월 10 ~ 5월 13일간 본인이 설정할 목표를 적어주세요.

### ISSUE THREAD

**Issue by jithhuP** [jithhuP/PowerBall#25]
본인이 할 수 있는 목표를 설정해두며 조금씩 하자는 의미로 만든 issue입니다.
작은 작업도 괜찮습니다.

**Comment by jithhuP** [comment]
13일까지 firebase 내용 수리, 필요한 데이터 정리해서 DB에 넣기
로또 기사 크롤링하기 -> firebase 혹은 web페이지로 제공할지 생각해보기.

**Comment by jominking** [comment]
막대 그래프 코딩한 것 git push 하기, 비율에 관한 원형 그래프 만들고 git push 하기
