### ISSUE TITLE
기초 디자인 설계(예시)와 역할 분담.

### ISSUE THREAD

**Issue by jithhuP** [jithhuP/PowerBall#3]
[기초 디자인 설계.pdf](https://github.com/jithhuP/PowerBall/files/11108820/default.pdf)

첫 Main 디자인과 확률 디자인 예시 표본입니다.
 
한분은 Main Page(1~2 페이지)를 맡을 예정이며, 한분은 통계 Page를 맡을 예정(3 페이지)입니다.
저는 여러분들이 Page 설계를 할 동안 필요 정보를 python Beautifulsoup을 활용하여 클로링 할 예정입니다. 저 또한 디자인 공부를 할 예정이니 도움이 필요한 경우 Issue를 통해 문의해주세요.

Main Page 역할 : 
통계 Page 역할 : 
데이터 크롤링 역할 : 윤정섭

원하신 내용이 있다면 댓글을 달아주세요.

**Comment by jithhuP** [comment]
통계 page 같은 경우, Main Page는 원하시는 방식으로 디자인 하셔도 좋습니다. 아직 구체적으로 디자인 한 것이 아닙니다. 다만 2번과 3번을 표시한 page 같은 경우, 최대한 비슷하게 구상할 수 있도록 노력해주세요. (더 좋은 디자인 구상이 있다면 바꾸셔도 상관 없습니다.)

**Comment by jominking** [comment]
확인했습니다. 디자인이나 다른 생각이 떠오르면 말씀 드리겠습니다.

**Comment by jominking** [comment]
제가 통계 부분 맡겠습니다.

**Comment by 1Parksanghyun** [comment]
제가 main 부분 맡겠습니다.
