### ISSUE TITLE
통계 부분 원형 그래프도 만들었습니다.

### ISSUE THREAD

**Issue by jominking** [jithhuP/PowerBall#31]
<img width="261" alt="image" src="https://github.com/jithhuP/PowerBall/assets/127294217/67439eab-789b-4f66-8f05-5817dd0fce32">

**Comment by 1Parksanghyun** [comment]
github에 게시 해주세요

**Comment by jominking** [comment]
올렸습니다. 근데 main과 연결되어 있지 않은데 상관없나요?

**Comment by 1Parksanghyun** [comment]
pull request 하시면 됩니다.

**Comment by jominking** [comment]
알겠습니다. 감사합니다!

**Comment by 1Parksanghyun** [comment]
pull request 지금 해주셔야 할 것 같습니다 가능하신가요?

**Comment by jominking** [comment]
![image](https://github.com/jithhuP/PowerBall/assets/127294217/349128b7-f3b2-4a02-84d8-800f476573ae)
음... 브랜치 시작 부분이 연결되어 있지 않아 request가 안되는 것 같습니다.
![image](https://github.com/jithhuP/PowerBall/assets/127294217/ab08d44d-9b84-4ccd-98ea-b64d0c1d57b5)

**Comment by 1Parksanghyun** [comment]
사진 다 나오게 다시 올려 주실수 있나요?

**Comment by 1Parksanghyun** [comment]
아니면 main_menu_final 로 request는 되나요?

**Comment by jominking** [comment]
final로도 request가 안되네요

**Comment by 1Parksanghyun** [comment]
final 에서 branch 새로 만드시고 지금까지 작업하신 것들
새로 만든 branch 에 복사하여 넣으시고 request 보내주세요

**Comment by jominking** [comment]
네, 해보겠습니다.

**Comment by jominking** [comment]
request 성공했습니다. 확인해주세요!
