### ISSUE TITLE
5월 14 ~ 5월 17일, 3일간 본인이 설정할 목표를 적어주세요

### ISSUE THREAD

**Issue by jithhuP** [jithhuP/PowerBall#33]
본인이 할 수 있는 목표를 설정해두며 조금씩 하자는 의미로 만든 issue입니다.
작은 작업도 괜찮습니다.

주의 : Commit을 할 때, 본인이 어떤 작업을 했는지 다른 사람이 보더라도 상세히 알 수 있도록 써주세요.
Push, pull 등 올리는 작업 혹은 합치는 작업에도 어떤 내용을 업데이트 하는 것인지 상세히 작성해주시기 바랍니다.

예시 : 시간 설정 완료 -> main페이지에 들어갈 시간 설정 완료. (수정파일 : 파일 이름)

모두들 열심히 개발해주셔서 감사합니다.

**Comment by jithhuP** [comment]
firebase에 DB 값이 제대로 들어가는지 확인 및 다른 기사 크롤링.
DB에 넣는 데이터를 정리

**Comment by jominking** [comment]
통계 부분 ui를 만들어보겠습니다.
