### ISSUE TITLE
import 경로 수정

### ISSUE THREAD

**Issue by 1Parksanghyun** [jithhuP/PowerBall#37]
fitty_pie_chart.dart
total_pie_chart.dart

해당 파일 import 부분 문제점 수정해주세요

해당 부분 외에 문제를 확인하시고 수정해주시길 바랍니다.

이슈 수정하실 때 분기 만드시고 해주세요

**Comment by jominking** [comment]
분기 만드는 것이 무엇인가요?

**Comment by jominking** [comment]
<img width="308" alt="image" src="https://github.com/jithhuP/PowerBall/assets/127294217/a02833cf-aa31-4cf4-9d3a-e23f7a7d9021">
경로 수정했습니다. 잘 되시는지 확인해주세요.
