### ISSUE TITLE
main menu에 통계 차트 적용

### ISSUE THREAD

**Issue by 1Parksanghyun** [jithhuP/PowerBall#38]
메인 화면에서 해당 되는 통계 차트 적용해주세요 

작업하시기 전에 main branch 에서 Pull 한번 수행하시고 branch 만든 다음 진행하시길 바랍니다.

또한, 가상환경 휴대폰으로 Pixel 2 API 30 으로 진행 해주시길 바랍니다.

**Comment by jominking** [comment]
넵, 확인했습니다.

**Comment by jithhuP** [comment]
확인했습니다.

**Comment by jominking** [comment]
넣었습니다.
