### ISSUE TITLE
기사 사이트 연결 시켜주세요

### ISSUE THREAD

**Issue by 1Parksanghyun** [jithhuP/PowerBall#47]
branch : Report_screen
파일 : custom_widget.dart
함수 : LinkArticle 

연결해야 하는 주소를 하나에 파일에 모아주시고 파일을 읽는 방식으로 하나씩 연결하여 생성해 주시길 바랍니다.
주소부분이 실제로 연결되는 사이트 입니다

**Comment by jithhuP** [comment]
내일 내로 기사 정보 및 링크 크롤링 firebase에 올리겠습니다.
