### ISSUE TITLE
Contributers 관련 알림

### ISSUE THREAD

**Issue by 1Parksanghyun** [jithhuP/PowerBall#9]
오늘 Main_menu_add branch 를 main branch 로 병합했더니
제가 짜지 않은 코드 4,461 줄이 제가 기여한것으로 간주되어있습니다
나중에 교수님께 제 코드 4,461줄은 제외 해달라고 말해주시길 바랍니다.

**Comment by jithhuP** [comment]
알겠습니다. 작업 수고하십니다.
